# Generated by Django 5.0.7 on 2024-07-17 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileintake', '0001_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubmission',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='useraccount.customeraccount'),
        ),
        migrations.AlterField(
            model_name='customermetadata',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='useraccount.customeraccount'),
        ),
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='useraccount.customeraccount'),
        ),
        migrations.DeleteModel(
            name='CustomerAccount',
        ),
    ]
