# Generated by Django 5.0.7 on 2024-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileintake', '0002_alter_documentsubmission_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='s3_key',
        ),
        migrations.AddField(
            model_name='document',
            name='upload_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='CustomerMetadata',
        ),
    ]
