# Generated by Django 5.0.7 on 2024-07-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_customermetadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='user',
        ),
    ]
